import { VetteObject } from "../types";

const fakeVettes: VetteObject[] = [
  {
    id: "1",
    year: "2014",
    miles: "123456",
    cost: "51000",
    exteriorColor: "Artic White",
    interiorColor: "Red",
    submodel: "Base",
    trim: "1LT",
    packages: ["NPP", "MRC", "PDR"],
    link: "www.google.com",
    transmissionType: "Automatic",
    date: "01-01-2023",
    userId: "user1",
  },
  {
    id: "2",
    year: "2015",
    miles: "31000",
    cost: "43000",
    exteriorColor: "Artic White",
    interiorColor: "Red",
    submodel: "Base",
    trim: "2LT",
    packages: ["NPP", "MRC", "PDR"],
    link: "www.google.com",
    transmissionType: "Manual",
    date: "02-01-2023",
    userId: "user2",
  },
  {
    id: "3",
    year: "2018",
    miles: "12000",
    cost: "47000",
    exteriorColor: "Artic White",
    interiorColor: "Red",
    submodel: "Base",
    trim: "3LT",
    packages: ["NPP", "MRC", "PDR"],
    link: "www.google.com",
    transmissionType: "Automatic",
    date: "03-01-2023",
    userId: "user3",
  },
  {
    id: "4",
    year: "2017",
    miles: "23421",
    cost: "45000",
    exteriorColor: "Artic White",
    interiorColor: "Red",
    submodel: "Base",
    trim: "2LT",
    packages: ["NPP", "MRC", "PDR"],
    link: "www.google.com",
    transmissionType: "Manual",
    date: "04-01-2023",
    userId: "user4",
  },
  {
    id: "5",
    year: "2015",
    miles: "42000",
    cost: "37000",
    exteriorColor: "Artic White",
    interiorColor: "Red",
    submodel: "Base",
    trim: "2LT",
    packages: ["NPP", "MRC", "PDR"],
    link: "www.google.com",
    transmissionType: "Automatic",
    date: "05-01-2023",
    userId: "user5",
  },
];

export default fakeVettes;
